### ISSUE TITLE
Criar estatísticas para uso dos Centros Cooperantes das redes LILACS e BVS

### ISSUE THREAD

**Issue by suelisuga** [bireme/data-governance#39]
Solicito criar visualização de dados estatísticos para Centros Cooperantes das redes LILACS e BVS.

Objetivo das visualizações:

- Gestão do trabalho de cooperação com as Fontes de Informação da BVS
- Prestação de contas à instituição
- Histórico da contribuição contextualizada nas diversas bases para as quais coopera e dentro de sua instituição
- Análise da produção científica e técnica da instituição 

Premissas:

- Apresentadas no idioma do CC
- Atualizadas diariamente e de forma automática
- Propiciar download dos dados em formato que propicie reuso como copiar e colar em uma tabela Excel ou inclusão em um documento Word.
- Fácil acesso
--Avaliar uma forma de acessar via FI-Admin no perfil de cada usuário
- Fácil compreensão
--Avaliar juntar registros hj separados por data de criação e atualização

### Prestação de contas à instituição
Visão **mensal** (data de criação e atualização)

Objetiva prover dados ao Centro Cooperante para que ele possa rapidamente prestar contas do trabalho realizado com a rede BIREME para a sua instituição.

Atende ao próprio Centro Cooperante e à sua instituição.

Destacar trabalho realizado para a LILACS, mas apresentar dados que separam sua contribuição para outras bases de dados da BVS.

Número de registros por:
- Total de registros por fonte de informação - LILACS e outras bases BVS, LIS, DirEve, Multimedia, Leyes y Recursos Educacionais Abiertos 

- LILACS e bases da BVS (Metadados>Indexado em e Biblioteca>Base de dados):
--Contribuição mensal nos últimos 12 meses
--Por status (rascunho, publicado, LLXP, recusado, apagado)
--Tipos de literatura e nível de tratamento (dados dos campos 5 e 6)
--Data de Publicação do documento
--País de Publicação
--Idioma
--Fascículo do periódico indexado pelo CC (nem todo CC tem periódico atribuído)
--Registros com textos completos

### Histórico da contribuição 
Visão **anual** (data de criação e atualização) – todo histórico da contribuição

Objetiva dar uma visão da evolução do CC dentro do contexto de suas contribuições anteriores e principais características da produção desse CC.

Atende ao próprio Centro Cooperante e à instituição

Destacar trabalho realizado para a LILACS, mas apresentar dados que separam sua contribuição para outras bases de dados da BVS.

Número de registros publicados por:
- Total de registros por fonte de informação - Registros bibliográficos, LIS, DirEve, Multimedia, Leyes y Recursos Educacionais Abiertos 

- Registros Bibliográficos (LILACS e bases da BVS) (campos Metadados>Indexado em e Biblioteca>Base de dados):
--Contribuição anual desde o ano de início da contribuição
--Por status (rascunho, publicado e LLXP)
--Tipos de literatura (M, N, T e S)
--Data de Publicação do documento
--País de Publicação
--Idioma
--Fascículo do periódico indexado pelo CC (nem todo CC tem periódico atribuído)
--Registros com textos completos

### Big picture institucional 
Visão **anual** (data de criação e atualização) – todo histórico da contribuição da instituição dentro de seu contexto, ou seja, todos os CC da USP, Unicamp, Unesp, Fiocruz, UFRJ, UFBA, etc. dentro do contexto de seu país

Objetiva mostrar a contribuição da instituição dentro de seu ecossistema e do país. Pode atender o próprio Centro Cooperante, a instituição, o editor do periódico da instituição e também um coordenador de rede.

Nessa visão os dados mostram a participação de todos os CCs da instituição e mostram dados da produção nacional registrada na LILACS e bases BVS
- Total de registros por fonte de informação - Registros bibliográficos, LIS, DirEve, Multimedia, Leyes y Recursos Educacionais Abiertos 

- Contribuição do CC considerando outros CC da instituição
- Tipos de literatura e nível de tratamento (5 e 6)
- Data de Publicação do documento
- País de Publicação
- Idioma
- Base de dados (Metadados>Indexado em e Biblioteca>Base de dados)
- Fascículo do periódico indexado pelo CC (nem todo CC tem periódico atribuído)
- Principais temas segundo os descritores de assunto
- Registros com textos completos

###  Gestão do trabalho: 
Visão **mensal** com dados referentes aos 12 últimos meses.

Apresentar dados de contribuição para o CC e o coordenador da Rede LILACS e BVS.

- Total de registros por fonte de informação - Registros bibliográficos, LIS, DirEve, Multimedia, Leyes y Recursos Educacionais Abiertos 

- Número de registros por data de criação e atualização:
- Usuário
- Status (Rascunho, LILACS-Express, Publicado, Apagado, Recusado)
- Tipo de contribuição (Entrada no FI-Admin, Migração, Submission, Coleta)
- Número de descritores primários, secundários, precodificados, tipos de publicação e qualificadores por registro
- Descritores e qualificadores mais utilizados
- Tempo dispendido em um registro bibliográfico - Hora de início e término do registro
- Dias e horários da semana em que acessa
- Número de artigos pendentes por fascículo do periódico LILACS-Express (nem todo CC tem periódico atribuído)
- Intervalo entre as contribuições (data entre a última contribuição e a atual)
- Tempo entre registro pendente (LLXP) e sua publicação pelo CC (revisão da descrição e indexação)
- Reuso de registros de outros centros
- Base de dados e indexado em
- Descritores
- Dados de acervo
- Registros com textos completos

### Big Picture na rede 
@renatomurasaki Tenho dúvidas se deveria ser como Gestão do Trabalho ou Big Picture Institucional... tem a ver com o uso... se mostrar mensal ou anual...

### Análise da produção científica e técnica da instituição: 
Visão integral da produção científica do CC
- Principais temas publicados
- Produção científica no decorrer do tempo
- Tipos de estudos mais publicados
- Autoria individual
- Coautoria
- Autoria em parceria com autores estrangeiros e outras instituições
- Registros com textos completos
- Perfis por tipo de literatura e nível de tratamento (5 e 6)
- Principais temas
- Idiomas
- Países
- Autoria
- Coautoria

@renatomurasaki entendo que terei que abrir um issue para cada tipo de cenário, mas queria ter uma issue que mostrasse tudo para revisarmos em conjunto.

Obrigada!
Sueli

**Comment by renatomurasaki** [comment]
Sueli, dividir cada visualização em um issue, por favor. Sobre idioma, o Tableau não gera interface configurável multo-idioma, o q nos resta criar uma visualização por idioma. Sugiro, nesse momento, criar em espanhol e uma vez criada se gera a mesma visualização com labels traduzidos. A atualização ainda não será diária e tampouco automática. Provavelmente mensal e manual, uma vez que isso depende de implementação da arquitetura de governança de dados e implementação das rotinas de ETL que estimo estar pronta no meio do segundo semestre. Exportação de dados será via o próprio Tableau. Será necessário gerar recurso de aprendizagem para explicar como isso se faz.

Sent from my iPhone

On 21 Feb 2019, at 18:30, Sueli Mitiko Yano Suga <notifications@github.com<mailto:notifications@github.com>> wrote:


Solicito criar visualização de dados estatísticos para Centros Cooperantes das redes LILACS e BVS.

Objetivo das visualizações:

  *   Gestão do trabalho de cooperação com as Fontes de Informação da BVS
  *   Prestação de contas à instituição
  *   Histórico da contribuição contextualizada nas diversas bases para as quais coopera e dentro de sua instituição
  *   Análise da produção científica e técnica da instituição

Premissas:

  *   Apresentadas no idioma do CC
  *   Atualizadas diariamente e de forma automática
  *   Propiciar download dos dados em formato que propicie reuso como copiar e colar em uma tabela Excel ou inclusão em um documento Word.
  *   Fácil acesso
--Avaliar uma forma de acessar via FI-Admin no perfil de cada usuário
  *   Fácil compreensão
--Avaliar juntar registros hj separados por data de criação e atualização

Prestação de contas à instituição

Visão mensal (data de criação e atualização)

Objetiva prover dados ao Centro Cooperante para que ele possa rapidamente prestar contas do trabalho realizado com a rede BIREME para a sua instituição.

Atende ao próprio Centro Cooperante e à sua instituição.

Destacar trabalho realizado para a LILACS, mas apresentar dados que separam sua contribuição para outras bases de dados da BVS.

Número de registros por:

  *   Total de registros por fonte de informação - LILACS e outras bases BVS, LIS, DirEve, Multimedia, Leyes y Recursos Educacionais Abiertos

  *   LILACS e bases da BVS (Metadados>Indexado em e Biblioteca>Base de dados):
--Contribuição mensal nos últimos 12 meses
--Por status (rascunho, publicado, LLXP, recusado, apagado)
--Tipos de literatura e nível de tratamento (dados dos campos 5 e 6)
--Data de Publicação do documento
--País de Publicação
--Idioma
--Fascículo do periódico indexado pelo CC (nem todo CC tem periódico atribuído)
--Registros com textos completos

Histórico da contribuição

Visão anual (data de criação e atualização) – todo histórico da contribuição

Objetiva dar uma visão da evolução do CC dentro do contexto de suas contribuições anteriores e principais características da produção desse CC.

Atende ao próprio Centro Cooperante e à instituição

Destacar trabalho realizado para a LILACS, mas apresentar dados que separam sua contribuição para outras bases de dados da BVS.

Número de registros publicados por:

  *   Total de registros por fonte de informação - Registros bibliográficos, LIS, DirEve, Multimedia, Leyes y Recursos Educacionais Abiertos

  *   Registros Bibliográficos (LILACS e bases da BVS) (campos Metadados>Indexado em e Biblioteca>Base de dados):
--Contribuição anual desde o ano de início da contribuição
--Por status (rascunho, publicado e LLXP)
--Tipos de literatura (M, N, T e S)
--Data de Publicação do documento
--País de Publicação
--Idioma
--Fascículo do periódico indexado pelo CC (nem todo CC tem periódico atribuído)
--Registros com textos completos

Big picture institucional

Visão anual (data de criação e atualização) – todo histórico da contribuição da instituição dentro de seu contexto, ou seja, todos os CC da USP, Unicamp, Unesp, Fiocruz, UFRJ, UFBA, etc. dentro do contexto de seu país

Objetiva mostrar a contribuição da instituição dentro de seu ecossistema e do país. Pode atender o próprio Centro Cooperante, a instituição, o editor do periódico da instituição e também um coordenador de rede.

Nessa visão os dados mostram a participação de todos os CCs da instituição e mostram dados da produção nacional registrada na LILACS e bases BVS

  *   Total de registros por fonte de informação - Registros bibliográficos, LIS, DirEve, Multimedia, Leyes y Recursos Educacionais Abiertos

  *   Contribuição do CC considerando outros CC da instituição

  *   Tipos de literatura e nível de tratamento (5 e 6)

  *   Data de Publicação do documento

  *   País de Publicação

  *   Idioma

  *   Base de dados (Metadados>Indexado em e Biblioteca>Base de dados)

  *   Fascículo do periódico indexado pelo CC (nem todo CC tem periódico atribuído)

  *   Principais temas segundo os descritores de assunto

  *   Registros com textos completos

Gestão do trabalho:

Visão mensal com dados referentes aos 12 últimos meses.

Apresentar dados de contribuição para o CC e o coordenador da Rede LILACS e BVS.

  *   Total de registros por fonte de informação - Registros bibliográficos, LIS, DirEve, Multimedia, Leyes y Recursos Educacionais Abiertos

  *   Número de registros por data de criação e atualização:

  *   Usuário

  *   Status (Rascunho, LILACS-Express, Publicado, Apagado, Recusado)

  *   Tipo de contribuição (Entrada no FI-Admin, Migração, Submission, Coleta)

  *   Número de descritores primários, secundários, precodificados, tipos de publicação e qualificadores por registro

  *   Descritores e qualificadores mais utilizados

  *   Tempo dispendido em um registro bibliográfico - Hora de início e término do registro

  *   Dias e horários da semana em que acessa

  *   Número de artigos pendentes por fascículo do periódico LILACS-Express (nem todo CC tem periódico atribuído)

  *   Intervalo entre as contribuições (data entre a última contribuição e a atual)

  *   Tempo entre registro pendente (LLXP) e sua publicação pelo CC (revisão da descrição e indexação)

  *   Reuso de registros de outros centros

  *   Base de dados e indexado em

  *   Descritores

  *   Dados de acervo

  *   Registros com textos completos

Big Picture na rede

@renatomurasaki<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frenatomurasaki&data=02%7C01%7Cmurasaki%40paho.org%7C7b9ccc0b501f48d72a5908d69843d31c%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C636863814416640287&sdata=6IXTv1%2BEGGEr0pSHVVVpBElCrsdLMRmcaSX0yOd7SGQ%3D&reserved=0> Tenho dúvidas se deveria ser como Gestão do Trabalho ou Big Picture Institucional... tem a ver com o uso... se mostrar mensal ou anual...

Análise da produção científica e técnica da instituição:

Visão integral da produção científica do CC

  *   Principais temas publicados
  *   Produção científica no decorrer do tempo
  *   Tipos de estudos mais publicados
  *   Autoria individual
  *   Coautoria
  *   Autoria em parceria com autores estrangeiros e outras instituições
  *   Registros com textos completos
  *   Perfis por tipo de literatura e nível de tratamento (5 e 6)
  *   Principais temas
  *   Idiomas
  *   Países
  *   Autoria
  *   Coautoria

@renatomurasaki<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frenatomurasaki&data=02%7C01%7Cmurasaki%40paho.org%7C7b9ccc0b501f48d72a5908d69843d31c%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C636863814416640287&sdata=6IXTv1%2BEGGEr0pSHVVVpBElCrsdLMRmcaSX0yOd7SGQ%3D&reserved=0> entendo que terei que abrir um issue para cada tipo de cenário, mas queria ter uma issue que mostrasse tudo para revisarmos em conjunto.

Obrigada!
Sueli

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fdata-governance%2Fissues%2F39&data=02%7C01%7Cmurasaki%40paho.org%7C7b9ccc0b501f48d72a5908d69843d31c%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C636863814416650291&sdata=L7LgiAZh8oqHUIGgVKetTaZUyZ0ZPQN4yCEanFYSAiU%3D&reserved=0>, or mute the thread<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABK16qHs6x5yL-qeDMiFCqMooGpkaTcrks5vPw_8gaJpZM4bIXaB&data=02%7C01%7Cmurasaki%40paho.org%7C7b9ccc0b501f48d72a5908d69843d31c%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C636863814416650291&sdata=Jv72TVKaRkJ%2BgjyzLIqaP1FdUQNKbvIB9b2J4RVhE58%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by suelisuga** [comment]
Subdivisão em visualização para CC que engloba contextos institucionais e redes: #40

**Comment by suelisuga** [comment]
Subdivisão em visualização da produção científica para CC que engloba contextos institucionais e redes: #41

**Comment by suelisuga** [comment]
Subdivisão em visualização da gestão do trabalho de contribuição com LILACS e bases da BVS para o CC e Coordenadores de rede criado: #42

**Comment by suelisuga** [comment]
Issue da tabela de instituições e redes criado #43
